// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xolmxsozkwkkthtjrlwt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhvbG14c296a3dra3RodGpybHd0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMxMDIyNTUsImV4cCI6MjA2ODY3ODI1NX0.w8xT_JSVNHCZITQtQT2eTAV-__dGgPyUwtve53xr9mw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);